export {default as HomePage} from './HomePage'
export {default as CalibrationHomePage} from './CalibrationDepartment/CalibrationHomePage'
export {default as ThermalHomePage} from './ThermalDepartment/ThermalHomePage'
export {default as HVACHomePage} from './HVACDepartment/HVACHomePage'
export {default as Location} from './Location'